### ISSUE TITLE
请问这个公私钥是在哪里生成并配置呢，我按照说明中提到的环境变量配置在ide启动配置里没有生效。是不是要配置在系统中。

### ISSUE THREAD

**Issue by wxywh** [Tencent/bk-job#1128]
请问这个公私钥是在哪里生成并配置呢，我按照说明中提到的环境变量配置在ide启动配置里没有生效。是不是要配置在系统中。
另外我看到模板中有很多yml文件，正常是不是都是要复制到磁盘根目录下的data/bkee中
我的开发环境是windows

_Originally posted by @wxywh in https://github.com/Tencent/bk-job/issues/1064#issuecomment-1167647180_

**Comment by wangyu096** [comment]
你好，这个公私钥是蓝鲸部署的时候运维脚本生成的。您可以找一套部署完成之后的蓝鲸社区版，参考下配置并修改
