### ISSUE TITLE
hotfix: 应该提示下个性化--脚本模板的作用范围及时机

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1322]
参考文案 仅对当前用户有效. 快速执行脚本和新建脚本会用到此模板.
![image](https://user-images.githubusercontent.com/54015094/191030828-0dedfe75-a965-4f8b-938b-1bc0c95f37fe.png)

**Comment by nekzhang** [comment]
指引文案：
`ZH` 脚本模板仅对当前用户在新建脚本相关场景下有效（如快速执行脚本、新建脚本、作业脚本步骤）
`EN` Script template is only valid for the current user in scenarios related to new scripts (e.g. Quick script execution, New scripts, New job script steps)
