### ISSUE TITLE
perf:【下次处理】【JOB】【一般】全局变量结尾的使用全局变量文案不合适。而且为什么突然要处理json？

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1323]
应该描述为如下3步：
1. 如何声明魔法变量： #import行 {{变量名}}
2. 告知用户魔法变量生效的效果等价于：变量名=json编码的内容， 实例如下。
3. 使用魔法变量需要处理json。
而魔法变量的支持场景则单独列表说明：
1. 全局变量里的主机列表。
2. 上一步骤的成功失败主机列表。
3. 上一步骤？的命名空间变量聚类结果。
![image](https://user-images.githubusercontent.com/54015094/191031666-ced78619-72d7-40a1-a56b-61ff8c724687.png)

**Comment by nekzhang** [comment]
将shell处理json字符串的段落单独拎出来一个小标题（如”变量列表“标题），标题名为 `处理建议`（英文：`Suggestions`）
