### ISSUE TITLE
【下次处理】【JOB】【一般】新建版本“未保存”时，如果有更新内容，鼠标点到其他版本时，会弹出保存。但是我测试到，针对版本信息的变更，会弹窗；但是针对脚本的变更，不会弹窗。bugfix: 

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1327]
![image](https://user-images.githubusercontent.com/54015094/191254885-7224d277-a819-418c-846e-e1b4c8b69dac.png)
![image](https://user-images.githubusercontent.com/54015094/191255005-d79879ed-99c4-4035-9434-1d306639394d.png)

**Comment by nekzhang** [comment]
已在第一期的【必须解决】中处理了，issue closed
