### ISSUE TITLE
【下次处理】【JOB】【一般】当通过脚本引用的方式，引用了一个脚本，此时不会提示有高危语句。但是提交执行时，会被拦截。（建议此处也要有提示）

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1329]
![image](https://user-images.githubusercontent.com/54015094/191256095-ccf5efcb-5460-41cd-9f6b-1e2b3a42e03a.png)
![image](https://user-images.githubusercontent.com/54015094/191256130-0696eb9d-d7c3-4d2b-bf50-cf6532d6d45e.png)

**Comment by nekzhang** [comment]
已在一期的【必须解决】迭代中处理，issue closed.
