### ISSUE TITLE
【下次处理】【JOB】【一般】翻译有缺失的情况

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1331]
![image](https://user-images.githubusercontent.com/54015094/191264910-d1d017c6-413b-4b68-a116-de254e1979d7.png)
![image](https://user-images.githubusercontent.com/54015094/191264918-f04f6f6b-a512-4c2a-ab8f-c102331f991b.png)

**Comment by nekzhang** [comment]
无需处理！显示非英文的原因是切换语言后没有刷新页面，实际翻译文本是存在的，故issue closed.
