### ISSUE TITLE
hotfix: 点击版本对比，跳转到的页面并非对比页面，用户不知道该对比啥

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1343]
![image](https://user-images.githubusercontent.com/54015094/191266299-08671126-036a-4140-bf2e-f29cd3094a8e.png)
![image](https://user-images.githubusercontent.com/54015094/191266311-105c4b78-fcce-4e32-81a9-90c1537fa198.png)

**Comment by nekzhang** [comment]
点击 `版本对比` 后直接弹出代码对比框，但版本号不可选择
