### ISSUE TITLE
feature:作业平台能否提供ssh通道或telnet通道

### ISSUE THREAD

**Issue by xieliangcai** [Tencent/bk-job#1411]
在未安装agent的网络设备或服务器上，通过ssh或telnet去执行命令

**Comment by nekzhang** [comment]
目前蓝鲸平台对OS的管控都是基于agent之上，暂时没有提供类似 `堡垒机` 通过ssh通道登录OS操作的工具，未来是否会有目前无法肯定的答复你，推荐关注下我们的 [官网](https://bk.tencent.com/) 了解最新的产品动态，感谢支持 🌹
