### ISSUE TITLE
bugfix: 本地文件上传大小限制可以输入负数

### ISSUE THREAD

**Issue by jsonwan** [Tencent/bk-job#1445]
**Version / Branch / tag**
3.5.x

**出了什么问题？(What Happened?)**
本地文件上传大小限制可以输入负数

**如何复现？(How to reproduce?)**
本地文件上传大小限制输入负数并提交

**预期结果(What you expect?)**
本地文件上传大小限制输入负数时提示非法，只能输入大于0的浮点数

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/207530246-6d8dcffb-854c-40e3-a14b-34fbe05ccdff.png)
