### ISSUE TITLE
bugfix: 数据库账号的端口可以输入负数

### ISSUE THREAD

**Issue by jsonwan** [Tencent/bk-job#1446]
**Version / Branch / tag**
3.5.x

**出了什么问题？(What Happened?)**
数据库账号的端口可以输入负数

**如何复现？(How to reproduce?)**
创建数据库账号时端口输入负数并提交

**预期结果(What you expect?)**
数据库账号的端口输入负数时提示非法，只能输入0及以上的整数

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/207530142-45cec5d3-a88f-4a07-9dbf-e71bb797004c.png)
