### ISSUE TITLE
bugfix: 本地文件分发报错

### ISSUE THREAD

**Issue by wangyu096** [Tencent/bk-job#1592]
**Version / Branch / tag**

3.6.1-alpha.1

**出了什么问题？(What Happened?)**
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/28581184/206386724-55f8a9af-de85-4319-9436-39091f02f1fb.png">

报错如下：
<img width="1747" alt="image" src="https://user-images.githubusercontent.com/28581184/206386907-1fda5194-ed7a-466f-82aa-5178d00095d9.png">

**如何复现？(How to reproduce?)**

必现

**预期结果(What you expect?)**
本地文件分发正常

**Comment by wangyu096** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/28581184/206387120-c6051614-3c2f-49e9-9f69-a8aed1123b09.png">
执行过程中没有获取到源主机的信息。这里的sourceHost是从step_instance_file.file_source字段来的，查询DB发现这个字段中没有主机信息，应该是文件准备阶段没有设置源主机信息

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/206956156-7a83ac4b-0fe8-4a14-a738-d8bd957d6fbb.png)

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
