### ISSUE TITLE
feature: 定时任务编辑主机变量时要打开”结果预览“的变更标签

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1667]
![image](https://user-images.githubusercontent.com/54015094/211319886-8c655c87-b77f-41cf-85eb-14c34894d183.png)

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/217750342-726e20aa-5557-4a0f-acbe-c77257ef0983.png)
