### ISSUE TITLE
【必须】JOB-用魔法变量测试了下主机列表类型的变量 

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1677]
●同时有IPv4和IPv6时，只会输出IPv4地址，而且有两条IPv4的输出。
![image](https://user-images.githubusercontent.com/54015094/211321961-66d623c8-a9dd-4a0a-b185-89e535b75735.png)
![image](https://user-images.githubusercontent.com/54015094/211322035-2950a73e-e22e-45db-8e61-8649033b391b.png)
●只有IPv6时，输出null
![image](https://user-images.githubusercontent.com/54015094/211322118-d4cba458-8a11-42e8-b411-9d78ceeabfbf.png)
![image](https://user-images.githubusercontent.com/54015094/211322171-2c8832de-3ee5-4191-8a58-9e642f391938.png)
![image](https://user-images.githubusercontent.com/54015094/211322274-68949e1e-5128-4e5e-809a-2d77f72ea48d.png)

**Comment by nekzhang** [comment]
输出2条的问题由GSE-AGENT解决，输出为null的问题已在另一个issue中解决
