### ISSUE TITLE
【必须】JOB-复制IP的逻辑确认，显示复制了4个，实际上粘贴只有3个，因为1个没有IPv4（或者是否能选择复制 IPv6）具体调整看评论

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1680]
![image](https://user-images.githubusercontent.com/54015094/211322727-d1ef1d33-7fd1-4f8b-a2d0-1bc2a928259c.png)

**Comment by vuuv** [comment]
复制IP的按钮只能悬停出现，点击后不会有反应。
建议兼容悬停和点击。
