### ISSUE TITLE
【必须】JOB-文本一致性问题 （详见评论区）

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1681]
![image](https://user-images.githubusercontent.com/54015094/211322824-7724125a-afea-42a5-aa69-7d46416f581b.png)

**Comment by nekzhang** [comment]
选项整体调整为：​

复制所有
    └─ IPv4
    └─ IPv6
复制异常
    └─ IPv4
    └─ IPv6
清除所有
清除异常
