### ISSUE TITLE
bugfix: 步骤执行详情导出日志的那个confirm弹窗现在显示不出来了

### ISSUE THREAD

**Issue by nekzhang** [Tencent/bk-job#1690]
**Version / Branch / tag**
3.7.0

**出了什么问题？(What Happened?)**
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/3852595/211999178-b6224984-b326-4d61-bd0b-86aad6d4d015.png">

导出日志的那个confirm弹窗现在显示不出来了

**如何复现？(How to reproduce?)**
点击“导出日志”按钮

**预期结果(What you expect?)**
<img width="647" alt="image" src="https://user-images.githubusercontent.com/3852595/211998897-40b271dc-3a1b-491e-ac3c-9345498fbbd3.png">

**Comment by vuuv** [comment]
第一次直接下载，重复点击会有确认。
