### ISSUE TITLE
作业平台脚本参数可执行高危命令

### ISSUE THREAD

**Issue by tingyu-bian** [Tencent/bk-job#237]
使用脚本执行功能中时，在脚本参数框内可编写高危命令，后续在脚本内可执行。
![}(24II7@A_R{~C3JEQS LRK](https://user-images.githubusercontent.com/49895683/133570263-975e0a38-b212-4a7e-8ce7-c44f2564ae45.png)
![微信截图_20210916153622](https://user-images.githubusercontent.com/49895683/133570367-eb5ebfb1-02a2-4aca-a2a8-246a0a53c797.png)

**Comment by nekzhang** [comment]
因为JOB执行任务本身并不是通过自研或侵入OS脚本解释器来实现，所以一些用户通过引用目标机器本地文件的脚本内容、或者其他变量方式传参来拼凑成高危语句的场景，目前JOB cover不了。
