### ISSUE TITLE
docs: ESB V3接口operate_step_instance的operation_code参数取值描述不正确

### ISSUE THREAD

**Issue by jsonwan** [Tencent/bk-job#244]
需要检查下其他接口是否有类似问题

**Comment by wangyu096** [comment]
##### operation_code 详细说明
| operation_code | 操作类型 | 适用步骤 | 描述 |
|-----------|------------|--------|------------|
| 2  | 失败IP重做   | 脚本执行，文件分发步骤 | 对失败的IP重新下发任务 |
| 3  | 忽略错误     | 脚本执行，文件分发步骤 | 忽略错误，继续执行     |
| 6  | 确认继续     | 人工确认步骤           | 确认继续执行           |
| 8  | 全部重试     | 脚本执行，文件分发步骤 | 对所有的IP重新下发任务 |
| 9  | 终止确认流程 | 人工确认步骤           | 确认终止执行           |
| 10 | 重新发起确认 | 人工确认步骤           | 重新发起确认           |
| 11 | 进入下一步   | 脚本执行，文件分发步骤 | 当步骤状态为终止成功，用于继续执行后续步骤 |
| 12 | 强制跳过     | 脚本执行，文件分发步骤 | 当步骤状态为终止中，用于强制跳过当前步骤，执行后续步骤|
