### ISSUE TITLE
feature: add docker support

### ISSUE THREAD

**Issue by llitfkitfk** [Tencent/bk-job#36]
- [x] add docker support for frontend
- [ ] add docker support for backend
- [ ] add docker compose support for local development

**Comment by wangyu096** [comment]
@llitfkitfk 感谢您提的issue。
蓝鲸作业平台下半年会进行容器化的支持。作为蓝鲸的底层原子平台之一，我们的容器化实现需要遵循蓝鲸容器化的规范来实现，现阶段正在规划中，后续job会按照蓝鲸统一的标准来实现。

**Comment by llitfkitfk** [comment]
好的

**Comment by llitfkitfk** [comment]
现在的结构编译需要依赖DB链接 
这样对于Docker的multi-stage构建不太友好

我是现在的做法是本地打包,将jar包放入镜像内
