### ISSUE TITLE
feature: get_job_instance_status接口返回优化,新增当前执行步骤的信息

### ISSUE THREAD

**Issue by cxsofware** [Tencent/bk-job#468]
接口返回优化:
1.需要知道作业到哪一个步骤了
2.需要知道这个作业执行全部成功的ip和失败的ip

**Comment by wangyu096** [comment]
需求1：需要知道作业到哪一个步骤了
考虑了下，这个地方job不适合给出明确的当前执行步骤的判断。原因如下：
1. 当前步骤可能存在多个（目前job是串行执行的，所以当前只有一个；后续迭代我们可能会支持多个步骤并行执行
2. 调用方其实已经能够从step_instance 的 status 字段判定正在执行的步骤

所以，个人觉得，直接job给出当前执行步骤，一方面也只是对当前数据的二次包装，另外却限制了以后的扩展性。

问题2： 需要知道这个作业执行全部成功的ip和失败的ip
这个只要在API传入return_ip_result即可获取的每个ip的任务的状态

**Comment by wangyu096** [comment]
按照沟通，用户侧解决，job本身不适合根据场景做API定制
