### ISSUE TITLE
bugfix: 执行方案的变量引用检测逻辑缺漏

### ISSUE THREAD

**Issue by nekzhang** [Tencent/bk-job#572]
**版本/分支/tag**
V3.4.3

**问题描述**
![image](https://user-images.githubusercontent.com/3852595/147541078-ea0d7f05-aac0-4799-9fee-29b29881d93e.png)

![image](https://user-images.githubusercontent.com/3852595/147541157-a3351f31-c92b-41b4-9b3a-a0c159f8b11c.png)

${project_id} 没有命中

**如何复现**

**预期结果**
不应该出现在“未引用变量”里

**Comment by wangyu096** [comment]
原因：
解析变量的正则表达式使用了贪婪模式，会最大匹配。错误代码如下：
```
Matcher m2 = Pattern.compile("\\$\\{[#!]?([_a-zA-Z][0-9_a-zA-Z]*)\\S*}").matcher(content);
```
比如：
'{"id":"'${cluster_id}'","project_id":"'${project_id}'"}'，期望的是解析到cluster_id和project_id两个变量，而在贪婪模式下，会解析到${cluster_id}'","project_id":"'${project_id}这一串字符，大括号会一直匹配到该行的最后一个}

**Comment by wangyu096** [comment]
done.
version: 3.4.4
