### ISSUE TITLE
job子服务启动

### ISSUE THREAD

**Issue by jiaohongtao** [Tencent/bk-job#650]
job的子服务 job-config 启动成功，但是其他服务都有这个问题，例如这个 job-manage 报错提示日志如下，要怎么解决呢
![image](https://user-images.githubusercontent.com/44717089/150985112-23d15d6b-386c-4faf-bf7d-b23f5f18f51e.png)
![image](https://user-images.githubusercontent.com/44717089/150985270-70ed79bb-698d-4c07-b390-d52f5600f615.png)
![image](https://user-images.githubusercontent.com/44717089/150985302-0b000d0f-afc3-4194-9de5-ef15cc05644e.png)

**Comment by wangyu096** [comment]
麻烦系统下版本信息。这个问题应该是配置文件有问题

**Comment by jiaohongtao** [comment]
这个问题已经解决了，是因为common的基础配置的问题，现在前后端代理连接不正确

**Comment by jiaohongtao** [comment]
> 麻烦提供下版本信息。这个问题应该是配置文件有问题

这个问题已经解决了，是因为common的基础配置的问题，现在前后端代理连接不正确 用的是master分支的1.0.0版本

页面请求的时候访问了两个IP，是不是哪里配置的有问题呢，或者 {{ -- }} 这个里面代理的是不是有问题呢，麻烦帮忙看一下呢

这几个变量不知道具体要配置什么，麻烦给说一下呢
JOB_API_GATEWAY_URL
JOB_EXTERNAL_THEME
JOB_API_HOST
JOB_GATEWAY_IP0 （为什么有两个呢，还有一个IP1，这个要配置那个服务的IP和端口呢）

页面
![image](https://user-images.githubusercontent.com/44717089/151123431-da3a2505-a5e7-4cf4-a700-7f07041968b7.png)
nginx
![image](https://user-images.githubusercontent.com/44717089/151123524-63351c39-ef7e-4045-87f5-1be50ed7ffc1.png)
index.html
![image](https://user-images.githubusercontent.com/44717089/151123587-a9e1d38d-a142-490f-8efd-73666c74906d.png)

**Comment by wangyu096** [comment]
已解决
