### ISSUE TITLE
docs: 部署文档应该更新

### ISSUE THREAD

**Issue by NoviceMao** [Tencent/bk-job#770]
编译后的jar包和文档中的不一样
版本bk-job-3.4.5.5编译的jar包
![image](https://user-images.githubusercontent.com/65475570/161360062-c3bb5e3f-d1bc-4c72-8f5f-bafd9444aac0.png)
文档中的jar包
![image](https://user-images.githubusercontent.com/65475570/161360143-449b9dca-0460-4537-88f0-8b0b52bb5033.png)

**Comment by jsonwan** [comment]
感谢反馈，我们更新下。

**Comment by jsonwan** [comment]
已更新，后续若发现有类似问题，欢迎提Issue，也可直接提PR。
