### ISSUE TITLE
能否提供Java版SDK

### ISSUE THREAD

**Issue by liyin** [Tencent/bk-job#849]
随着7.0的到来，平台支持容器方式部署，理论上可以支持所有开发语言（包括Java）做SaaS开发。
但没有示例使用java开发SaaS——其中难点在于没有调用 API 的Java版SDK。
正好 bk-job 是java版的应用，里面有一些调用平台的jar。是否可以写一个文档，或做一个示例，让Java版的SaaS开发成为可能。

**Comment by wangyu096** [comment]
你好，请问您是需要JAVA SDK版本的 Job API 么？还是需要所有平台的

**Comment by liyin** [comment]
JAVA SDK 能调用到所有API最好，与Python SDK的能力对等也很OK。这样就可以用Java做SaaS开发了。

**Comment by wangyu096** [comment]
@liyin 跟相关平台了解了下，目前Java SDK 是没有的。这个目前来说只能自己写代码去调用API，不过这个也不复杂
