### ISSUE TITLE
bugfix: 高危语句动作为扫描时,且脚本存在高危语句无法执行

### ISSUE THREAD

**Issue by wangyu096** [Tencent/bk-job#866]
**Version / Branch / tag**

3.4.6
**出了什么问题？(What Happened?)**
![image](https://user-images.githubusercontent.com/28581184/165277157-9d7932a6-c8f9-40a8-a540-fc58fd0e55b6.png)
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/28581184/165277277-d81f6188-dad7-45f0-a7bb-3da0ecad04e1.png">

**如何复现？(How to reproduce?)**
见问题描述

**预期结果(What you expect?)**
把快速执行脚本页面对高危语句规则的处理逻辑和第三方系统调用保持一致；（即，如果是扫描的，仅做提示，用户可以选择继续执行），文案如下：
![image](https://user-images.githubusercontent.com/28581184/165277409-5f5db255-3770-4a13-a084-26fe743da737.png)
点“继续执行”时，则正常继续下发任务；
点“立即取消”时，返回页面。

**Comment by nekzhang** [comment]
警告！脚本中出现高危语句（详见编辑框左侧  图标的提示） 请确定是否要继续操作？
Warning!!! High-risk grammar has found in the script (see the icon on the leftside of the script editor), Are you sure want to proceed?

[确定继续]  [立即取消]
[YES] [NO]
