### ISSUE TITLE
perf: 业务拓扑需要调整为自然排序

### ISSUE THREAD

**Issue by nekzhang** [Tencent/bk-job#969]
JOB：
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/3852595/170646812-4be3c777-3f0f-47f2-a722-3f0a91f82a0e.png">
CMDB：
<img width="554" alt="image" src="https://user-images.githubusercontent.com/3852595/170646889-5ca4e125-3ced-438b-bdee-96256a19498a.png">

排序方式与CMDB保持一致：
1. 空闲机池始终第一位
2. 其他的按自然序进行排列

**Comment by jsonwan** [comment]
除空闲机池以外的拓扑节点顺序由CMDB接口数据决定：/api/c/compapi/v2/cc/get_biz_brief_cache_topo/

**Comment by jsonwan** [comment]
3.6版本已处理
